name: Init repository
description: Initialize the repository for the build

runs:
  using: 'composite'
  steps:
    - uses: fregante/setup-git-user@v2
    - uses: actions/setup-node@v4
      with:
        node-version: 24
        registry-url: 'https://registry.npmjs.org'
    - name: Setup Clang for Linux
      shell: bash
      run: |
        echo "CC=clang"   >> $GITHUB_ENV
        echo "CXX=clang++" >> $GITHUB_ENV
        echo "CXXFLAGS=-std=c++20 -fexceptions" >> $GITHUB_ENV
    - name: Install dependencies
      run: npm i
      shell: bash
