name: Commit and push
description: Commit and push changes to the repository

inputs:
  ref:
    required: false
    default: 'main'
  message:
    required: true
  token:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Commit and push
      shell: bash
      run: |
        git add .
        git commit -m "${{ inputs.message }}"
        git push origin ${{ inputs.ref }}
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
